# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Digibox Web Admin CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Digital Ocean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/digibox-web-admin
            git remote set-url origin git@github.com:RatchanikornCompany/digibox-web-admin.git
            git fetch -p
            git add .
            gut commit -m "new commit digibox web admin"
            git pull origin main
            docker-compose down
            docker system prune -f
            docker-compose up -d --build
            docker ps -a
